### ISSUE TITLE
Issue with PlayerDeathEvent 

### ISSUE THREAD

**Issue by MissLaia** [JEFF-Media-GbR/Spigot-AngelChest#4]
Hey, I have a issue with the plugin.When the players die, they spawn with the full inventory and the chest never spawn.

[12:34:25 ERROR]: Could not pass event PlayerDeathEvent to AngelChest v1.4.0
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:419) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at net.minecraft.server.v1_13_R2.EntityPlayer.die(EntityPlayer.java:493) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1055) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity(EntityHuman.java:799) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at net.minecraft.server.v1_13_R2.EntityPlayer.damageEntity(EntityPlayer.java:622) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at net.minecraft.server.v1_13_R2.Entity.burnFromLava(Entity.java:505) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at net.minecraft.server.v1_13_R2.Entity.W(Entity.java:459) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at net.minecraft.server.v1_13_R2.EntityLiving.W(EntityLiving.java:210) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at net.minecraft.server.v1_13_R2.Entity.tick(Entity.java:332) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2023) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at net.minecraft.server.v1_13_R2.EntityHuman.tick(EntityHuman.java:151) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:381) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at net.minecraft.server.v1_13_R2.PlayerConnection.Y_(PlayerConnection.java:140) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:231) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:120) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:994) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.util.MissingFormatArgumentException: Format specifier '%s'
at java.util.Formatter.format(Formatter.java:2519) ~[?:1.8.0_45-internal]
at java.util.Formatter.format(Formatter.java:2455) ~[?:1.8.0_45-internal]
at java.lang.String.format(String.java:2928) ~[?:1.8.0_45-internal]
at de.jeffclan.AngelChest.AngelChest.‹init›(AngelChest.java:26) ~[?:?]
at de.jeffclan.AngelChest.PlayerListener.onPlayerDeath(PlayerListener.java:123) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45-internal]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45-internal]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[gbinvl_spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
... 23 more

**Comment by mfnalex** [comment]
You have your config file wrong. "Caused by: java.util.MissingFormatArgumentException: Format specifier '%s'"

Please see the original config file at the spigotmc.org page or delete your config.yml file and restart your server. Some messages have to contain "%s", as that is a placeholder for information in the message.
