### ISSUE TITLE
can't enable 2.22.1

### ISSUE THREAD

**Issue by Boastful1353** [JEFF-Media-GbR/Spigot-AngelChest#48]
[06:11:59] [Server thread/ERROR]: Error occurred while enabling AngelChest v2.22.1 (Is it up to date?)
java.lang.NullPointerException: null
	at java.util.UUID.fromString(UUID.java:197) ~[?:?]
	at de.jeff_media.AngelChest.AngelChest.<init>(AngelChest.java:59) ~[?:?]
	at de.jeff_media.AngelChest.Main.loadAllAngelChestsFromFile(Main.java:204) ~[?:?]
	at de.jeff_media.AngelChest.Main.onEnable(Main.java:73) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-"1c8b6065e"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-"1c8b6065e"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-"1c8b6065e"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-"1c8b6065e"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-"1c8b6065e"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.5.jar:git-Paper-"1c8b6065e"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.5.jar:git-Paper-"1c8b6065e"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935) ~[patched_1.16.5.jar:git-Paper-"1c8b6065e"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-"1c8b6065e"]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by AcesGamingUK** [comment]
please send full log,
the output of `/version`
and the output of `/version angelchest`

**Comment by Boastful1353** [comment]
Clearly there is no output of /version angel-chest because it didn't enable. Also both version strings are right there in the error.

AngelChest v2.22.1

patched_1.16.5.jar:git-Paper-"1c8b6065e"

It must be something you changed in the plugin during the last few versions made my configuration invalid i skipped a few versions and updated directly to 1.22.1 i just renamed the plugin folder and the newly generated config worked.

**Comment by AcesGamingUK** [comment]
and the full latest.log?

**Comment by mfnalex** [comment]
why did you close? did you get it fixed?
