### ISSUE TITLE
Duplication of items

### ISSUE THREAD

**Issue by Sakanas** [JEFF-Media-GbR/Spigot-AngelChest#9]
It duplicates SlimeFun items that have SOULBOUND, (SOULBOUND serves to keep iten after death) if it had any way to put NTB's blacklist item to be ignored.

**Comment by mfnalex** [comment]
I will investigate this in a few days, currently I don‘t have much time. Thanks for the bug reports :)

**Comment by mfnalex** [comment]
Do you mean this plugin? https://dev.bukkit.org/projects/slimefun

**Comment by mfnalex** [comment]
SlimeFun is broken, badly coded (using Reflection and stuff) and not being developed anymore. On using SlimeFun, I instantly got this:

```
[09:54:19 INFO]: [AngelChest] Checking for available updates...
[09:54:19 INFO]: [AngelChest] You are using the latest version of AngelChest.
[09:54:22 WARN]:
[09:54:22 WARN]: #################### - INFO - ####################
[09:54:22 WARN]:
[09:54:22 WARN]: Please restart your Server to finish the Installation
[09:54:22 WARN]: of Slimefun and CS-CoreLib
[09:54:22 WARN]:
[09:54:22 WARN]: #################### - INFO - ####################
[09:54:22 WARN]:
stop
[09:55:51 INFO]: Stopping the server
[09:55:51 INFO]: Stopping server
[09:55:51 INFO]: [WorldGuard] Disabling WorldGuard v7.0.0-SNAPSHOT;1754-9169653
[09:55:51 INFO]: [WorldGuard] Shutting down executor and waiting for any pending                                                                                                                               tasks...
[09:55:51 INFO]: [Slimefun] Disabling Slimefun vv4.1.15
[09:55:51 ERROR]: Error occurred while disabling Slimefun vv4.1.15 (Is it up to                                                                                                                               date?)
java.lang.NullPointerException: null
        at me.mrCookieSlime.Slimefun.SlimefunStartup.onDisable(SlimefunStartup.j                                                                                                                              ava:404) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[s                                                                                                                              pigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoade                                                                                                                              r.java:363) [spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManag                                                                                                                              er.java:422) [spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginMana                                                                                                                              ger.java:415) [spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServe                                                                                                                              r.java:365) [spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.ja                                                                                                                              va:625) [spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.jav                                                                                                                              a:770) [spigot-1.13.2.jar:git-Spigot-2474d93-ca22de3]
        at java.lang.Thread.run(Unknown Source) [?:?]
[09:55:51 INFO]: [Drop2Inventory] Disabling Drop2Inventory v2.1
[09:55:51 INFO]: [AngelChest] Disabling AngelChest v1.5.1
[09:55:51 INFO]: [WorldEdit] Disabling WorldEdit v7.0.0-SNAPSHOT;3935-f0070c1
[09:55:51 INFO]: [LightPerms] Disabling LightPerms v1.0
[09:55:51 INFO]: Saving players
[09:55:51 INFO]: Saving worlds
[09:55:51 INFO]: Saving chunks for level 'world_the_end'/minecraft:the_end
[09:55:51 INFO]: Saving chunks for level 'world'/minecraft:overworld
[09:55:51 INFO]: Saving chunks for level 'world_nether'/minecraft:the_nether
```
I don't think I will invest time into supporting an abandoned plugin that uses Reflection (a pain in the ass!).

**Comment by Sakanas** [comment]
slimefun 1.13 > https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/
cs-corelib 1.13 >https://thebusybiscuit.github.io/builds/TheBusyBiscuit/CS-CoreLib/master/

**Comment by mfnalex** [comment]
As I said, I will not add support for this, sorry. I will only support plugins that use the Spigot API and no net.minecraft.server classes and methods, because they change with every update.

**Comment by Sakanas** [comment]
so I would put a disable world option?

**Comment by Sakanas** [comment]
Is it not possible to do something or ignore the item by custom name?

ignoreitem:
  - skull-notch
  - diamond-namecuston

**Comment by mfnalex** [comment]
Of course you can disable AngelChest for specific worlds.

**Comment by mfnalex** [comment]
Can you provide a screenshot of one of the items that you want to be ignored?
